<a href="https://colab.research.google.com/github/matcha-jillyace/FORMELOZA_3B_CSST101/blob/main/FORMELOZA_CSST101_Exer3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create the student Database

In [1]:
students <- data.frame(
  Student_ID = c("S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008"),
  Programming_Grade = c(88, 72, 91, 78, 65, 85, 74, 82),
  Math_Grade = c(85, 70, 88, 80, 68, 90, 73, 79),
  Attendance = c(92, 80, 95, 88, 70, 91, 76, 85),
  Prerequisite = c("Yes", "No", "Yes", "Yes", "No", "Yes", "No", "Yes")
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes

2. Explore the Data

In [2]:
nrow(students)
ncol(students)

max(students$Attendance)
max(students$Math_Grade)
max(students$Programming_Grade)

min(students$Attendance)
min(students$Math_Grade)
min(students$Programming_Grade)

mean(students$Attendance)
mean(students$Math_Grade)
mean(students$Programming_Grade)

[1] 8

[1] 5

[1] 95

[1] 90

[1] 91

[1] 70

[1] 68

[1] 65

[1] 84.625

[1] 79.125

[1] 79.375

3. Enter a Student ID

In [3]:
student_id <- readline("Enter Student ID: ")
print(student_id)

Enter Student ID: S006
[1] "S006"

4. Search the Data Frame

In [4]:
student <- students [
  students$Student_ID == student_id,
]
student

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
6 S006       85                90         91         Yes

5. Check if the Students Exists

In [5]:
if (nrow(student) > 0){
  print("Student Found:")
  print(student)
}else{
print("Student ID not found.")
}

[1] "Student Found:"
  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
6       S006                85         90         91          Yes

6. Extract Student Information

In [6]:
programming <- students$Programming_Grade

cat("Programming Grade: ", programming)

math <- students$Math_Grade

cat("\nMath Grade: ", programming)

programming <- students$Attendance

cat("\nAttendance: ", programming)

math <- students$Prerequisite

cat("\nPrerequisite: ", programming)

Programming Grade:  88 72 91 78 65 85 74 82
Math Grade:  88 72 91 78 65 85 74 82
Attendance:  92 80 95 88 70 91 76 85
Prerequisite:  92 80 95 88 70 91 76 85

7. Implement the Rules

Rule 1: Eligible - Programming Grade >= 80 AND Math Grade >= 75 AND Attendance >= 80% AND Prerequisite = Yes.

Rule 2: Conditionally Eligible - Programming Grade >= 75 AND Math Grade >= 70 AND Attendance >= 75% but Rule 1 is not satisfied.

Rule 3: Not Eligible - if neither Rule 1 or Rule 2 is satisfied, classify the students as Not ELigible.

In [7]:
check_eligibility <- function(programming,math, attendance, prereq) {

  if (programming >= 80 &&
    math >= 75 &&
    attendance >= 80 &&
    prereq == "Yes") {
      return ("Eligible")

    } else if (programming >= 75 &&
      math >= 70 &&
      attendance >= 75) {
        return("Conditional Eligible")

      }else{
        return("Not Eligible")
      }
}

8. Check Eligibility

In [8]:
students$Eligibility <- mapply(
  check_eligibility,
  students$Programming_Grade,
  students$Math_Grade,
  students$Attendance,
  students$Prerequisite
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Eligibility
1 Eligible
2 Not Eligible
3 Eligible
4 Conditional Eligible
5 Not Eligible
6 Eligible
7 Not Eligible
8 Eligible

9. Create Recommendation Rules

1. Eligible - Student may enroll

2. Conditionally Eligible - Consult Academic Adviser

3. Not Eligible - Complete Requirements before enrollment

In [15]:
generate_recommendation <- function(eligibility) {
  if (eligibility == "Eligible") {
    return("Student may enroll")
  } else if (eligibility == "Conditional Eligible") {
    return("Consult Academic Adviser")
  } else {
    return("Complete Requirements before enrollment")
  }
}

Apply the Functions to All Students

In [16]:
students$Recommendation <- mapply(
  generate_recommendation,
  students$Eligibility
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Eligibility          Recommendation
1 Eligible             Student may enroll
2 Not Eligible         Complete Requirements before enrollment
3 Eligible             Student may enroll
4 Conditional Eligible Consult Academic Adviser
5 Not Eligible         Complete Requirements before enrollment
6 Eligible             Student may enroll
7 Not Eligible         Complete Requirements before enrollment
8 Eligible             Student may enroll

Result

In [17]:
student_id <- readline(prompt = "Enter Student ID: ")

student <- students[students$Student_ID == student_id, ]

if (nrow(student) > 0) {

  cat("\n========================================\n")
  cat("       COURSE ENROLLMENT ADVISER\n")
  cat("========================================\n\n")

  cat("Student ID:", student$Student_ID, "\n\n")

  cat("Programming Grade:", student$Programming_Grade, "\n")
  cat("Math Grade:", student$Math_Grade, "\n")
  cat("Attendance:", student$Attendance, "%\n")
  cat("Prerequisite:", student$Prerequisite, "\n\n")

  cat("Enrollment Status:\n")
  cat(student$Eligibility, "\n\n")

  cat("Recommendation:\n")
  cat(student$Recommendation, "\n")

  cat("========================================\n")

} else {
  cat("\nStudent ID not found.\n")
}

Enter Student ID: S006

========================================
       COURSE ENROLLMENT ADVISER
========================================

Student ID: S006

Programming Grade: 85
Math Grade: 90
Attendance: 91 %
Prerequisite: Yes

Enrollment Status:
Eligible

Recommendation:
Student may enroll
========================================